name: samtools_faidx
origin:
  repository: "http://www.htslib.org/"
  module_source: "nf-core/modules"
  original_authors:
      - "@drpatelh"
      - "@ewels"
      - "@phue"
  notes: |
    This module was originally developed in the nf-core ecosystem and
    has been adapted and versioned for the splice-nf-modules repository.  
description: Index FASTA file, and optionally generate a file of chromosome sizes
keywords:
  - index
  - fasta
  - faidx
  - chromosome
tools:
  - samtools:
      description: |
        SAMtools is a set of utilities for interacting with and post-processing
        short DNA sequence read alignments in the SAM, BAM and CRAM formats, written by Heng Li.
        These files are generated as output by short read aligners like BWA.
      homepage: http://www.htslib.org/
      documentation: http://www.htslib.org/doc/samtools.html
      doi: 10.1093/bioinformatics/btp352
      licence: ["MIT"]
      identifier: biotools:samtools
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing reference information
          e.g. [ id:'test' ]
    - fasta:
        type: file
        description: FASTA file
        pattern: "*.{fa,fasta}"
        ontologies: []
  - - meta2:
        type: map
        description: |
          Groovy Map containing reference information
          e.g. [ id:'test' ]
    - fai:
        type: file
        description: FASTA index file
        pattern: "*.{fai}"
        ontologies: []
  - get_sizes:
      type: boolean
      description: use cut to get the sizes of the index (true) or not (false)

output:
  fa:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.{fa,fasta}":
          type: file
          description: FASTA file
          pattern: "*.{fa}"
          ontologies: []
  sizes:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.sizes":
          type: file
          description: File containing chromosome lengths
          pattern: "*.{sizes}"
          ontologies: []
  fai:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.fai":
          type: file
          description: FASTA index file
          pattern: "*.{fai}"
          ontologies: []
  gzi:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.gzi":
          type: file
          description: Optional gzip index file for compressed inputs
          pattern: "*.gzi"
          ontologies: []
  versions_samtools:
    - - ${task.process}:
          type: string
          description: The process the versions were collected from
      - samtools:
          type: string
          description: The tool name
      - "samtools version | sed '1!d;s/.* //'":
          type: string
          description: The command used to generate the version of the tool

topics:
  versions:
    - - ${task.process}:
          type: string
          description: The process the versions were collected from
      - samtools:
          type: string
          description: The tool name
      - "samtools version | sed '1!d;s/.* //'":
          type: string
          description: The command used to generate the version of the tool
authors:
  - "@HR-cruk"
  - "@drpatelh"
  - "@ewels"
  - "@phue"
maintainers:
  - "@HR-cruk"
  - "@siddhathjayaraman"