name: picard_markduplicates
origin:
  repository: "https://github.com/broadinstitute/picard"
  module_source: "nf-core/modules"
  original_authors:
    - "@drpatelh"
    - "@projectoriented"
    - "@ramprasadn"
  notes: |
    This module was originally developed in the nf-core ecosystem and
    has been adapted and versioned for the splice-nf-modules repository.
description: Locate and tag duplicate reads in a BAM file
keywords:
  - markduplicates
  - pcr
  - duplicates
  - bam
  - sam
  - cram
tools:
  - picard:
      description: |
        A set of command line tools (in Java) for manipulating high-throughput sequencing (HTS)
        data and formats such as SAM/BAM/CRAM and VCF.
      homepage: https://broadinstitute.github.io/picard/
      documentation: https://broadinstitute.github.io/picard/
      licence: ["MIT"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - reads:
      type: file
      description: Sequence reads file, can be SAM/BAM/CRAM format
      pattern: "*.{bam,cram,sam}"
  - meta2:
      type: map
      description: |
        Groovy Map containing reference information
        e.g. [ id:'genome' ]
  - fasta:
      type: file
      description: Reference genome fasta file, required for CRAM input
      pattern: "*.{fasta,fa}"
  - meta3:
      type: map
      description: |
        Groovy Map containing reference information
        e.g. [ id:'genome' ]
  - fai:
      type: file
      description: Reference genome fasta index
      pattern: "*.{fai}"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - bam:
      type: file
      description: BAM file with duplicate reads marked/removed
      pattern: "*.{bam}"
  - bai:
      type: file
      description: An optional BAM index file. If desired, --CREATE_INDEX must be passed as a flag
      pattern: "*.{bai}"
  - cram:
      type: file
      description: Output CRAM file
      pattern: "*.{cram}"
  - metrics:
      type: file
      description: Duplicate metrics file generated by picard
      pattern: "*.{metrics.txt}"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@drpatelh"
  - "@projectoriented"
  - "@ramprasadn"
  - "@HR-cruk"
maintainers:
  - "@HR-cruk"
  - "@siddharthjayaraman"