name: untar
origin:
  repository: "https://github.com/coreutils/coreutils"
  module_source: "nf-core/modules/untar"
  original_authors:
    - "@joseespinosa"
  notes: |
    This module was originally developed in the nf-core ecosystem and
    has been adapted and versioned for the splice-nf-modules repository.
description: Extract files from tar, tar.gz, tar.bz2, tar.xz archives
keywords:
  - untar
  - uncompress
  - extract
tools:
  - untar:
      description: |
        Extract tar, tar.gz, tar.bz2, tar.xz files.
      documentation: https://www.gnu.org/software/tar/manual/
      licence: ["GPL-3.0-or-later"]
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - archive:
        type: file
        description: File to be untarred
        pattern: "*.{tar,tar.gz,tar.bz2,tar.xz}"
        ontologies:
          - edam: http://edamontology.org/format_3981 # TAR format
          - edam: http://edamontology.org/format_3989 # GZIP format
output:
  untar:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
          pattern: "*/"
      - ${prefix}:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
          pattern: "*/"
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: "versions.yml"
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
authors:
  - "@joseespinosa"
  - "HR-cruk"
maintainers:
  - "@HR-cruk"
  - "@siddharthjayaraman"