name: "fq_lint"
origin:
  repository: "https://github.com/stjude-rust-labs/fq"
  module_source: "nf-core/modules"
  original_authors:
    - "@adamrtalbot"
  notes: |
    This module was originally developed in the nf-core ecosystem and
    has been adapted and versioned for the splice-nf-modules repository.  
description: fq lint is a FASTQ file pair validator.
keywords:
  - lint
  - fastq
  - validate
tools:
  - "fq":
      description: "fq is a library to generate and validate FASTQ file pairs."
      homepage: "https://github.com/stjude-rust-labs/fq"
      documentation: "https://github.com/stjude-rust-labs/fq"
      tool_dev_url: "https://github.com/stjude-rust-labs/fq"
      licence: ["MIT"]
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - fastq:
        type: file
        description: FASTQ file list
        pattern: "*.fastq{,.gz}"
        ontologies: []
output:
  lint:
    - - meta:
          type: file
          description: Lint output
          pattern: "*.fq_lint.txt"
          ontologies: []
      - "*.fq_lint.txt":
          type: file
          description: Lint output
          pattern: "*.fq_lint.txt"
          ontologies: []
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: "versions.yml"
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
authors:
  - "@adamrtalbot"
  - "@siddharthjayaraman"
maintainers:
  - "@siddharthjayaraman"
